/******************************************************************************************
 *******************************************************
                                            VEHICLE RENTAL SYSTEM 
                        COMPILED ON : WINDOWS(G++) WITH C++ STANDARDS
*******************************************************************************************
********************************************************/

/* Include custom headers */
#include "application.h"
/* Include standard cpp headers */
#include <iostream>

using namespace std; 

int main (int argc, const char * argv[]) {

    Application * application = new Application () ;
    application->start();
}